# Generated by Django 4.2.7 on 2024-09-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0002_alter_category_options_alter_list_item_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['date_created']},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='creator_id',
            new_name='creator',
        ),
        migrations.AddField(
            model_name='category',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
