# Generated by Django 4.2.7 on 2024-09-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0011_alter_category_creator_alter_listitem_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='current',
            field=models.BooleanField(default=True),
        ),
    ]
