# Generated by Django 4.2.7 on 2024-09-07 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0012_listitem_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='preferred_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopping_list.shop'),
        ),
    ]
