# Generated by Django 4.2.7 on 2024-09-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0013_listitem_preferred_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='type_of_shop',
            field=models.IntegerField(choices=[(1, 'Supermarket'), (2, 'Organic shop'), (3, 'DIY center'), (4, 'Drugstore'), (5, 'Stationer'), (7, 'Flatpack furniture'), (8, 'Deli & fine foods'), (6, 'Specialist retailer')]),
        ),
    ]
