# Generated by Django 5.1.3 on 2024-11-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0015_alter_shop_type_of_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
