# Generated by Django 5.1.3 on 2024-11-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0019_auto_20241113_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
